import os
import shutil
import time

# --- CONFIG ---
# Paths for your SERVER directory structure
SOURCE_DIR = r"C:\Users\kevin\Documents\iCAM TD100 SDK\Recognition"
TARGET_DIR = r"C:\Users\kevin\Downloads\openiris-base-SERVER\openiris-base-SERVER\dataset2\Enhance"

def move_latest_frames():
    """
    Looks for numbered frames from the iCAM SDK (e.g., L_frame_0002.png).
    Renames and moves them to the processing folder for the matcher.
    """
    if not os.path.exists(TARGET_DIR):
        os.makedirs(TARGET_DIR)

    try:
        # 1. Look for the numbered frames generated by IcamBridge.exe
        l_frames = [f for f in os.listdir(SOURCE_DIR) if f.startswith("L_frame_") and f.endswith(".png")]
        r_frames = [f for f in os.listdir(SOURCE_DIR) if f.startswith("R_frame_") and f.endswith(".png")]
        
        if l_frames and r_frames:
            # 2. Grab the most recent capture (highest frame number)
            l_name = sorted(l_frames)[-1]
            r_name = sorted(r_frames)[-1]
            
            l_src = os.path.join(SOURCE_DIR, l_name)
            r_src = os.path.join(SOURCE_DIR, r_name)
            
            # 3. Move and rename to the standard 'probe' names for match_unity.py
            shutil.move(l_src, os.path.join(TARGET_DIR, "probe_L.png"))
            shutil.move(r_src, os.path.join(TARGET_DIR, "probe_R.png"))
            
            print(f"[PREP] Processed and moved: {l_name} and {r_name}")
            
            # 4. Clean up any remaining frames in the SDK folder
            for extra in os.listdir(SOURCE_DIR):
                if extra.endswith(".png"):
                    try:
                        os.remove(os.path.join(SOURCE_DIR, extra))
                    except:
                        pass
            return True
            
    except Exception as e:
        print(f"[PREP ERROR] {e}")
        
    return False